01 added sucess code

diff --git a/.github/workflows/01-building-block.yaml b/.github/workflows/01-building-block.yaml
--- a/.github/workflows/01-building-block.yaml
+++ b/.github/workflows/01-building-block.yaml
@@ -2,7 +2,6 @@ name: 01-building-blocks
 on: 
   - push
   - workflow_dispatch
-
 jobs:
   echo-hello:
     runs-on: ubuntu-latest
@@ -14,9 +13,9 @@ jobs:
     steps:
       - name: Failed steps
         run: |
+          #echo "This step will fail"
+          #exit 1 
           echo "This step will fail"
-          exit 1
+          exit 0
       - name: Say GoodBye
         run: echo "GoodBye"
-
-
